### ISSUE TITLE
red colored lines in curly braces (looks like errors)

### ISSUE THREAD

**Issue by TertiumOrganum1** [lucperkins/vrl-vscode#6]
If i write almost any code in curly braces it is red colored like errors, why? 
I even installed language server (no idea how it is related to this plugin), but almost everything is red.
The code has no errors and works in pipeline, so this is plugin problem.

![image](https://github.com/lucperkins/vrl-vscode/assets/51286827/1e07d1a2-a074-452c-97d0-a41ca21cf1c9)

**Comment by lucperkins** [comment]
This is indeed a shortcoming of the extension at the moment, as noted in #1. Unfortunately, I've moved on from the Vector project but am happy to take PRs addressing it. Closing this issue as redundant (though still present).

**Comment by TertiumOrganum1** [comment]
by the way how can I build the latest version? version on market is 2 years
old

пт, 26 апр. 2024 г., 22:16 Luc Perkins ***@***.***>:

**Comment by lucperkins** [comment]
@TertiumOrganum1 I'll try to get that aspect fixed this weekend

**Comment by TertiumOrganum1** [comment]
thanx!

пт, 26 апр. 2024 г., 22:49 Luc Perkins ***@***.***>:
